### ISSUE TITLE
PPT

### ISSUE THREAD

**Issue by Marsman1996** [Marsman1996/PoSS#12]

**Comment by Marsman1996** [comment]
键盘钩子+反虚拟机+反汇编+注册表自启动 演示录屏：

> 链接：https://pan.baidu.com/s/1v64tfgDpUPXHivK6p9sC-g 密码：zpi8

**Comment by liupuz** [comment]
PPT

链接：https://pan.baidu.com/s/1C47C1cirGrwm2XWT_R5s7Q 
提取码：pu6j

**Comment by Marsman1996** [comment]
汇报版PPT
链接：https://pan.baidu.com/s/1KIkXiNuXhaYEVWP0_QITqw 密码：bahe
